<?php

/**
 * @file
 * Main Mollom integration module functions.
 */

/**
 * Implements hook_menu().
 */
function mollom_menu() {
  $items['admin/config/content/mollom'] = array(
    'title' => 'Mollom content moderation',
    'description' => 'Configure how the Mollom service moderates user-submitted content such as spam and profanity.',
    'route_name' => 'mollom.config',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function mollom_permission() {
  return array(
    'administer mollom' => array(
      'title' => t('Administer Mollom-protected forms and Mollom settings'),
    ),
    'bypass mollom protection' => array(
      'title' => t('Bypass Mollom protection on forms'),
    ),
    'access mollom statistics' => array(
      'title' => t('View Mollom statistics'),
    ),
    'report to mollom' => array(
      'title' => t('Report content as inappropriate'),
    )
  );
}
